--[==[
	You sit on a seat, I guess.
	Note that seats can be used in interesting ways, as no matter where you touch the part from, you will always sit on the "top" of the seat.
	This means you can transport a player instantaneously with no physics interactions,
	Or create psuedo-timed sections by forcing the player back on to the seat after a set interval.
	
	Seats have one attribute, `SitCooldown`, which is the time it takes for the seat to become "sittable" after getting off of.
]==]