--[[

-Don't worry about this if your tower doesn't lag at all
(DO NOT USE IT FOR CREATING NEW GAMEPLAY MECHANICS, THIS WILL GET YOUR TOWER DISQUALIFIED)




-Put a client object in here and it will only move while your character is within a set distance from it
-There is a DefaultDistance value in the ClientObjectScript
-Putting a "CustomDistance" value in a client object will have that client object use that distance instead of the DefaultDistance value

--]]