--[==[
	!! This object can be activated by triggers!
	Boosters are parts that provide a temporary jump/speed boost when touched.

	Attributes:
		- Type: Whether the boost pad effects walkspeed or jump power; "Jump" for jump, "Speed" for speed, and "Both" for both.
		- BoostLength: The length (in seconds) the boost is applied for. Set to -1 to disable.
		- WalkSpeed/JumpPower: The power of the boost. The humanoid values are directly set from these with no changes.
]==]