--[==[
	!! This part can be activated by triggers!
	Button Deactivators are incredibly simple. 
	Just set the `ButtonGroupId` to the button group you wish to disable, and touching the deactivator will unpress all of the buttons in the group.
	Most of the work here is done by the Button object itself.
	
	**This is a touch activated object. Please read the "Touch Activated Objects" documentation in General Info for additional attributes.**
]==]