--[==[
	Conveyors are, well, conveyors. They move objects along them at a set speed.
	Note that conveyors may behave unpredictably when not anchored due to roblox engine quirks that I have not yet sorted out.
	
	Attributes:
		- ReplicateSpeedVisually: When true, the beam on the conveyor will move at the same speed as the `Speed` attribute.
		- Speed: The speed, in studs/s, that objects move along the conveyor.
]==]