--[==[
	Gravity Zones, unlike gravity changers, apply a seperate gravitational force in it's area seperate from the workspace gravity.
	Not much to it configuration wise but there's a lot of potential for cool things!!

	**This is a touch activated object. Please read the "Touch Activated Objects" documentation in General Info for additional attributes.**
	Attributes:
		- Gravity: The target gravity inside of the gravity zone.
		- Priority: When part is intersecting multiple gravity zones, the zone with the highest priority will be favoured.
			Use this option when you're stacking zones on top of one another
]==]