--[[ 
Kosta's Mini Tower Mayhem Building Kit v6.2

Please, read the mini tower building rules in the discord (you should find them if you scroll up in #submissions)
Hopefully you know how to use studio and know all of its hotkeys and such.

CREDITS:
- Jukereise, for the keys, buttons, and speed boosters
- Knighterisk, for fixing the pushing platform trampolines and the falling platforms
- funwolf7, for the noclip tool provided in this kit
- Other various people, for a few items included in the kit set
- q6int, mobilator and khyernet for adding CCOs to the kit

INSTRUCTIONS ON HOW TO SET UP THE KIT:
1. Go to game settings, find "Avatar" tab and switch to R6.
2. In "Workspace", turn off "StreamingEnabled" for all COs to not disappear.
3. Also in "Workspace", find "PhysicsSteppingMethod" and switch it to "Fixed", then find "SignalBehavior" and switch it to "Default".
4. Open "Scripts & Items" group and move folders to their respective placements, don't forget to ungroup the folders!
5. Go to "MaterialService", scroll all the way down and untick "Use2022Materials".
6. Go to "Lighting" and switch "Technology" to "Future". The rest is up to you, but it's better to use Lighting Changers in the kit.
7. It's optional, but you can put "MusicModule" to "ServerScriptService" for better performance.

Alright, have fun!
--]]



--[[ 
UPDATE LOGS AND ONLY UPDATE LOGS DOWN BELOW

UPDATE LOG: v6.2
- Rearranged the kit to be a bit more accessible
- Changed how size changing platform works
- A lot of useful bugfixes and QoL improvements
- Removed one line in corner flip script so you can make uncollidable flip by simply making it ccf


UPDATE LOG: v6.1
- Added 2 new COs from JToH #epic-stuff channel
   - Air jump, as a replacement of double jump
   - Swinger & Swinger Dismounter
- Some small things such as
   - Button activated truss
   - Beam blocks being uncollidable by default
   - Default music in a mini tower
   - MT portal text is now brighter :0
- no bugfixes bc no bugs?????? 
   
UPDATE LOG: v6
- New client objects got added:
   - Clickable button is brought back and works like the regular one
   - Turret direction/velocity changer bc i forgot to add it in v5 
   - Input brick
   - Double jump brick 
- Some got removed:
   - Poison giver
   - Facing platform
   - Herobrine
- And some received changes:
   - Re-organized the layout of the kit (happens in every version at this point)
   - Reverted "gerald" to be an avatar reference again
   - Changed the color of one specific item
   - Added heal bricks that work like kill bricks
   - Other minor changes
- fixed some bugs OooOOoOooOO :ghost: :ghost: :ghost:

UPDATE LOG: v5
- Added a ton of COs from JToH kit v5.5
- Added a few CCOs made by Quaintist and mobilator
- Cleaned up the kit hopefully
- Removed barriers

UPDATE LOG: v4.1
- Only bug fixes, mostly related to buttons.

UPDATE LOG: v4
- Rearranged the whole kit
- Added bunch of new objects:
   - Reference
   - Beam 
   - Mini tower portal
   - Slopifiers
   - Glow and color correction changers
   - One way platform
   - Clickable morphers
- Revamped some old COs
   - Moving platforms
   - Buttons
- And removed some
   - Inverse beat blocks
   - Point light givers
- Increased barrier area from 120x120 to 160x160
- Bug fixes

UPDATE LOG: v3.1.1
- Button deactivator fix and compatibility with click buttons
- Fixed whole frame being named Floor1

UPDATE LOG: v3.1
- Added corner clip 
- A lot of bug fixes and QoL changes to the kit.

UPDATE LOG: v3
- Increased frame to 25x125x25 and barrier area to 120x120
- Added toggle bricks
- Added click platform from ToPZ
- Added transporter (aka smooth tp)
- Added appearing platform (why)
- Welded everything broken
- Upgraded click button
- Obligatory bug fix
--]]