--[[
IF YOU DO NOT PUT THESE SCRIPTS IN THEIR RESPECTIVE PLACES MANY THINGS WILL NOT WORK
DamageEvent(script) and CollisonGroups go in ServerScriptService
DamageEvent(RemoteEvent) and ChangeLighting go in ReplicatedStorage
TouchScript goes in StarterCharacterScripts
LocalPartScript, PlayerModule and Flip go in StarterPlayerScripts (note that PlayerModule includes built-in mobile shiftlock)
EffectGUI goes in StarterGUI
--]]