--[==[
	BEFORE YOU START DOING ANYTHING, PLEASE FOLLOW THESE INSTRUCTIONS:
		- Set Workspace.PhysicsSteppingMethod to `Fixed`. If you don't do this, certain moving objects may break.
		- Set StarterPlayer.AutoJumpEnabled to `false`, 
			StarterGui.ScreenOrientation to `LandscapeSensor`, 
			and StarterPlayer.CharacterUseJumpPower to `true` if you don't want warnings.
		- Set MaterialService.Use2022Materials to `false` so that your tower will look the same as it would ingame.
		- Move EVERYTHING in the `SetupGroups` folder to where they ask to be put, and ungroup them.
		
	If you complain to me about anything without doing these steps first I will be very dissapointed in you. 
	I hope that is enough motivation.
	
	The rest of this folder contains documentation for each individual client object and other miscellaneous things that you may need.
	Please read through the documentation if you are struggling to understand how to use a particular client object.
	I will again be disappointed if you do not read the documentation before asking a question, but please tell me if it's unclear.
	
	THIS KIT HAS NOT YET BEEN BUG TESTED. YOU WILL RUN INTO BUGS. PLEASE REPORT THEM TO ME SO I CAN FIX THEM FOR THE NEXT RELEASE.
]==]