--[[NOTE THAT YOUR MUSIC ZONES SHOULD BE NAMED IN THE FOLLOWING FORMAT:
(mini tower acronym)(floor number or zone name)

-FOR EXAMPLE:
    -MToUGF1-2
	-MToDDTFS

-PLEASE DO THIS BEFORE SETTING THE ZONE NAME VALUE

-To "edit the sound id" of a music zone, you'll want to instead have two overlapping music zones, with the one that plays initially having a higher
priority value. You can then use this client object to edit the priority of the other music zone to be greater.]]
