--[==[
	Music Zones are pretty similar to EToH/JToH but they are structured slightly differently.
	Firstly, the priority of a music zone is an attribute of the music zone folder itself.
	Higher priority music zones will take priority over lower priority ones when determining which song to play.
	
	MUSIC ZONES ARE LOCKED BY DEFAULT, UNLOCK THEM IF YOU WANT TO MOVE THEM AROUND.
	
	If you wish to remove the music zones from workspace to avoid the parts being a giant pain,
	rename the MusicZones folder to "OToH Basic Kit" and place it under under SoundService.MusicZones.
	If you changed the name of the kit folder, you'll also have to change the name of the music zone folder.
	However, I have locked the music zones by default to avoid them being a hassle.
	
	**Reminder that you cannot use copyrighted music without permission.** 
	When submitting a tower, you will need to provide us with the audio files of songs you have uploaded yourself.
	If the song is not on the list of approved artists, you will also need to provide written permission from the artist
	that you are allowed to use the song in your tower.
]==]