--[==[
	If you intend to submit this tower to OToH, please follow these submission guidelines:
		- Your tower must abide by Roblox ToS (obviously).
		- Your tower must contain 6-12 floors (inclusive).
		- Your tower must not contain any floor design that may be excessively obnoxious to insert into the game.
			If there is legitimate reason to do so, you may submit it, but you will need a very good reason.
		- Your tower must not be submitted to other fangames. We will be paying you for your tower if it
			is put in game, so we would like you to respect our wish for exclusive rights to it as well.
		- You may not use copyrighted music in your tower without prior permission. 
			Yes, this is strict, but otherwise the game will end up in a grey area for copyright that could 
			get it struck down at any moment. We'd rather not run the risk.
		- You may not use any copyrighted media, trademarks, etc... in your tower. See above.
		- The part limit as of this kit version is (Floor Count)×450 parts. You may not exceed this in your submission.
			Too many parts will result in game lag, so we have to limit it, sorry.
		- You MAY bundle a custom portal design or portal room with your tower if you would like.
		
	If your tower is submitted in game, you will be paid 500-1000 robux per floor depending on length and quality.
	You will be paid an additional amount if you have composed or commissioned original music for the tower,
	as that is additional work we are obtaining rights for. The range for this varies too much to put a number on, however.
]==]